### PR TITLE
Backport from 10 to 9 version odoo muk_dmk_access

### PR DESCRIPTION
**Pull request by YuriiKhomych**
image
I backported your access module to 9 version odoo but catch one bug at your javascript side that I can`t change.
Please fix it if you can.
Thanks for you good application.

### CODE REVIEW

**Comment by YuriiKhomych** [comment]
Sorry)
I catch the bugs)

**Comment by keshrath** [comment]
If you want to reopen your pull request i can add it to the 9.0 branch

**Comment by YuriiKhomych** [comment]
I tried to backport from odoo 10 to 9 version but I take so many bugs in security module)

**Comment by YuriiKhomych** [comment]
Hi, I fix some bugs with security that didn`t work early.
But still have bugs with (Configuration>Access Control>New) view.
And when the user has no rules for read or write or create he anyway can change every file while he gets the warning like you can see at picture.
image
User can put 'ok' button and continue changing the file that must not allow our rules.
How are your rules for this module working?
And if you can fix this bug.

**Comment by keshrath** [comment]
hi, thx for the greate work! :) i will merge your request and will mark it as unstable. right now i'm quite bussy but I will try to look into your code and make it work :)

**Pull request merged**
