### PR TITLE
Added feature for versioning the file.

### PR DESCRIPTION
**Pull request by ajaychauhan727**
- Added feature for versioning the file

- Solve flake8 issue

### CODE REVIEW

**Comment by keshrath** [comment]
This PR changes a whole lot of code. What is the goal?

**Comment by ajaychauhan727** [comment]
Hi @keshrath,

With this PR, it will allow you to create a new file with the same name with new version mentioned on file form view.

Yes, I understand that in diff we can see too much code, but that's due to solving the flake8 issue I see in the file which I update. If you want I can remove that extra flake8 solving code to get this merged.

**Comment by keshrath** [comment]
In that case, I will not accept this PR. We already have an extension for the dms which adds file versioning.

**Comment by ajaychauhan727** [comment]
Hey @keshrath, Can you please provide me the link for that file versioning?

**Comment by keshrath** [comment]
https://apps.odoo.com/apps/modules/12.0/muk_dms_version/

**Pull request closed without merging**
